version: "3.8"

services:
  app:
    build: .
    container_name: minha_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped
    working_dir: /app  # opcional, ajuste conforme sua necessidade

  db:
    image: postgres:15
    container_name: meu_banco
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: minha_base
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data: